version: '3.8'

services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile.${MODE}
    container_name: frontend_c
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    stdin_open: true
    tty: true
    volumes:
      - ./:/app
    environment:
      - PORT=${PORT}
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - HOST=0.0.0.0
